### ISSUE TITLE
Stuck busy looping 

### ISSUE THREAD

**Issue by dpc** [alexcrichton/bzip2-rs#21]
First please take whit a grain of salt, and assume I might be doing something wrong, or the data is corrupted. 

I am doing long running `rdedup` stressttest I caught it hanged, using 100% of one of the CPUs. I was able to attach `gdb` and turns out it looping on a drop/`finish` in this code of mine: 

```
  8     fn decompress(&self, buf: SGData) -> io::Result<SGData> {                                                       
  7         let mut decompressor =                                                                                      
  6             bzip2::write::BzDecoder::new(Vec::with_capacity(buf.len()));                                            
  5                                                                                                                     
  4         for sg_part in buf.as_parts() {                                                                             
  3             decompressor.write_all(&sg_part)?;                                                                      
  2         }                                                                                                           
  1         Ok(SGData::from_single(decompressor.finish()?))                                                             
114     }
```

Note that 114 might be off, as I might have added/removed a line or two. I'm guessing it is `finish()` call.

```
#0  bzip2::write::{{impl}}::write<collections::vec::Vec<u8>> (self=0x7fff68365488, data=...)                            
    at /home/dpc/.cargo/registry/src/github.com-1ecc6299db9ec823/bzip2-0.3.2/src/write.rs:254                           
#1  0x00005567a4127d20 in core::ptr::drop_in_place<bzip2::write::BzDecoder<collections::vec::Vec<u8>>> ()               
    at /home/dpc/.cargo/registry/src/github.com-1ecc6299db9ec823/bzip2-0.3.2/src/write.rs:219                           
#2  0x00005567a4127952 in rdedup_lib::compression::{{impl}}::decompress (self=<optimized out>, buf=...)                 
    at lib/src/compression.rs:114                           
#3  0x00005567a4153913 in rdedup_lib::{{impl}}::read_chunk_into (self=0x7fff6837fd38, digest=...,                       
    chunk_type=<optimized out>, data_type=rdedup_lib::DataType::Data, writer=...) at lib/src/lib.rs:352                 
#4  0x00005567a4151807 in rdedup_lib::ReadContext::read_recursively (self=0x7fff68367aa0, accessor=..., digest=...)     
    at lib/src/lib.rs:262    
```

If I keep doing `next` in my `gdb`, I get:

```
core::ptr::drop_in_place<bzip2::write::BzDecoder<collections::vec::Vec<u8>>> ()                                         
    at /home/dpc/lab/rust/rdedup/lib/<try macros>:3         
3       /home/dpc/lab/rust/rdedup/lib/<try macros>: No such file or directory.                                          
(gdb)                         
218             while !self.done {                          
(gdb)                         
219                 try!(self.write(&[]));                  
(gdb)                         
3       /home/dpc/lab/rust/rdedup/lib/<try macros>: No such file or directory.                                          
(gdb)                         
218             while !self.done {                          
(gdb)                         
219                 try!(self.write(&[]));                  
(gdb) n                       
3       /home/dpc/lab/rust/rdedup/lib/<try macros>: No such file or directory.                                          
(gdb)                         
218             while !self.done {                          
(gdb)                         
219                 try!(self.write(&[]));                  
(gdb)                         
3       /home/dpc/lab/rust/rdedup/lib/<try macros>: No such file or directory.                                          
(gdb)                         
218             while !self.done {                          
(gdb)                         
219                 try!(self.write(&[]));                  
(gdb)                         
3       /home/dpc/lab/rust/rdedup/lib/<try macros>: No such file or directory.    
```

If I do `step`, I get:

```
3       /home/dpc/lab/rust/rdedup/lib/<try macros>: No such file or directory.                                          
(gdb) s                       
218             while !self.done {                          
(gdb)                         
219                 try!(self.write(&[]));                  
(gdb)                         
bzip2::write::{{impl}}::write<collections::vec::Vec<u8>> (self=0x7fff68365488, data=...)                                
    at /home/dpc/.cargo/registry/src/github.com-1ecc6299db9ec823/bzip2-0.3.2/src/write.rs:254                           
254             if self.done {
(gdb)                         
258                 try!(self.dump());                      
(gdb)                         
258                 try!(self.dump());                      
(gdb)                         
bzip2::write::BzDecoder<collections::vec::Vec<u8>>::dump<collections::vec::Vec<u8>> (self=0x7fff68365488)               
    at /home/dpc/.cargo/registry/src/github.com-1ecc6299db9ec823/bzip2-0.3.2/src/write.rs:200                           
200             while self.buf.len() > 0 {                  
(gdb)                         
204             Ok(())        
(gdb)                         
205         }                 
(gdb)                         
bzip2::write::{{impl}}::write<collections::vec::Vec<u8>> (self=0x7fff68365488, data=...)                                
    at /home/dpc/lab/rust/rdedup/lib/<try macros>:3                                                                     
3       /home/dpc/lab/rust/rdedup/lib/<try macros>: No such file or directory.                                          
(gdb)                                                                                                                   
267             (self.raw.total_in_lo32 as u64) |                                                                       
(gdb)                                                                                                                   
268             ((self.raw.total_in_hi32 as u64) << 32)                                                                 
(gdb)                                                                                                                   
261                 let res = self.data.decompress_vec(data, &mut self.buf);                                            
(gdb)                                                                                                                   
bzip2::mem::Decompress::decompress_vec (self=0x7fff68365488, input=..., output=0x7fff683654a8)                          
    at /home/dpc/.cargo/registry/src/github.com-1ecc6299db9ec823/bzip2-0.3.2/src/mem.rs:243                             
243                 let before = self.total_out();                                                                      
(gdb)                                                                                                                   
bzip2::mem::Decompress::total_out (self=<optimized out>)                                                                
    at /home/dpc/.cargo/registry/src/github.com-1ecc6299db9ec823/bzip2-0.3.2/src/mem.rs:243                             
243                 let before = self.total_out();                                                                      
(gdb)                         
bzip2::mem::Stream<bzip2::mem::DirDecompress>::total_out<bzip2::mem::DirDecompress> (self=<optimized out>)              
    at /home/dpc/.cargo/registry/src/github.com-1ecc6299db9ec823/bzip2-0.3.2/src/mem.rs:272                             
272             (self.raw.total_out_lo32 as u64) |          
(gdb)                         
273             ((self.raw.total_out_hi32 as u64) << 32)    
(gdb)                         
bzip2::mem::Decompress::decompress_vec (self=0x7fff68365488, input=..., output=0x7fff683654a8)                          
    at /home/dpc/.cargo/registry/src/github.com-1ecc6299db9ec823/bzip2-0.3.2/src/mem.rs:245                             
245                     let ptr = output.as_mut_ptr().offset(len as isize);                                             
(gdb)                         
core::ptr::{{impl}}::offset<u8> (count=<optimized out>, self=<optimized out>) at /checkout/src/libcore/ptr.rs:617       
617     /checkout/src/libcore/ptr.rs: No such file or directory.                                                        
(gdb)         
(...)
```

**Comment by alexcrichton** [comment]
Nah I'd definitely believe it, this has happened before!

Would you happen to have the data oh hand that caused this to reproduce?

**Comment by dpc** [comment]
Unfortunately, my tests are a higher level: generates random data, deduplicates it in rdedup, recovers it back, and compares the checksum. Since I have no good tracing and/or logging facilities, I don't have any nice, easy to digest information yet. I plan to add it but it will take a while.

If you can tell me what exactly would help (I am guessing the exact sequence of input pieces that lead to it), I could try to quick-hack something like that.

**Comment by dpc** [comment]
Also, I might be wrong about it, but I've seen data corruption problems before (that's what I am actually looking for), and since identifying this problem, I've blacklisted `bzip2` compression from my suite, and so far they are gone, so there might be more of them.

The only time where I was able to catch any issues were with the following `rdedup` settings:

```
target/release/rdedup init --chunking gear --chunk-size 2K --compression bzip2 --encryption curve25519 --hashing blake2b --nesting 0
target/release/rdedup init --chunking fastcdc --chunk-size 2K --compression bzip2 --encryption none --hashing blake2b --nesting 0
```
So I know that encryption is irrelevant, and I'm quite sure the problem reapears only (or with much higher probability) if I deal with a lot of small pieces of data (2K is the smallest chunking setting from my suite). It might take hours to catch one like these with rdedup, and it could be a combination of problems etc. so nothing here is conclusive, but I would advice to write a simple stresstester, that feeds `bzip` encoder small, random pieces of data in a stream, and then decrypts them back (again, in small random pieces if need be). This is pretty much what `rdedup` is doing, just with a lot of overhead of other pieces of deduplication.

I'll definitely keep you in loop when looking into it, but I will be busy in next two weeks.

**Comment by dpc** [comment]
The script has been running for 5 hours now, with `bzip2` disabled and all issues are gone, so I'm quite confident there are some other issues lurking in there.

**Comment by dpc** [comment]
I think it's a great opportunity for fuzzers and quickcheck. :)

**Comment by dpc** [comment]
I have finally got back from vacation and had some time to dive into it. The problem was entirely in `rdedup` and it must have been just some bad luck that bzip2 was failing. After fixing actual `rdedup` issues, I wasn't able to catch any issues, even witth `bzip2`, so I'm closing.

**Comment by alexcrichton** [comment]
Thanks for investigating!

**Comment by dpc** [comment]
So, I suspect, the busy looping part might be a problem with bzip2. The bugs I've fixed in rdedup were about data corruption, but I don't see how could they cause bzip2 to loop like described.

**Comment by alexcrichton** [comment]
Oh oops! Is there still sometimes a loop in bzip2?

**Comment by dpc** [comment]
I wasn't able to catch it but the original issue I reported was real so I am guessing it might still be there. If I catch it again I'll reopen.

**Comment by alexcrichton** [comment]
Ok, thanks!
