### ISSUE TITLE
Unclear how to cross-compile to Windows MSVC target from Linux

### ISSUE THREAD

**Issue by AaronM04** [alexcrichton/bzip2-rs#54]
I saw an error in my larger project when compiling with `--target=x86_64-pc-windows-msvc` on my Linux x86_64 host system:
```
error: failed to run custom build command for `bzip2-sys v0.1.7`

Caused by:
  process didn't exit successfully: `/home/x/dev/rust/life/conwayste/target/debug/build/bzip2-sys-94bcdbfb8c02afbc/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-pc-windows-msvc")
OPT_LEVEL = Some("2")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-pc-windows-msvc = None
CC_x86_64_pc_windows_msvc = None
TARGET_CC = None
CC = None
CROSS_COMPILE = None
CFLAGS_x86_64-pc-windows-msvc = None
CFLAGS_x86_64_pc_windows_msvc = None
TARGET_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "bzip2-1.0.6" "-D_WIN32" "-DBZ_EXPORT" "-D_FILE_OFFSET_BITS=64" "-DBZ_NO_STDIO" "/Fo/home/x/dev/rust/life/conwayste/target/x86_64-pc-windows-msvc/debug/build/bzip2-sys-79c995aba8afa54a/out/lib/bzip2-1.0.6/blocksort.o" "/c" "bzip2-1.0.6/blocksort.c"
cargo:warning=cc: error: /Fo/home/x/dev/rust/life/conwayste/target/x86_64-pc-windows-msvc/debug/build/bzip2-sys-79c995aba8afa54a/out/lib/bzip2-1.0.6/blocksort.o: No such file or directory
cargo:warning=cc: error: /c: No such file or directory
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "cc" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "bzip2-1.0.6" "-D_WIN32" "-DBZ_EXPORT" "-D_FILE_OFFSET_BITS=64" "-DBZ_NO_STDIO" "/Fo/home/x/dev/rust/life/conwayste/target/x86_64-pc-windows-msvc/debug/build/bzip2-sys-79c995aba8afa54a/out/lib/bzip2-1.0.6/blocksort.o" "/c" "bzip2-1.0.6/blocksort.c" with args "cc" did not execute successfully (status code exit code: 1).

', /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.28/src/lib.rs:2314:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:326
  13: cc::fail
             at /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.28/src/lib.rs:2314
  14: cc::Build::compile
             at /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.28/src/lib.rs:951
  15: build_script_build::main
             at ./build.rs:17
  16: std::rt::lang_start::{{closure}}
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  17: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  18: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  20: std::panicking::try
             at src/libstd/panicking.rs:270
  21: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  22: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  23: main
  24: __libc_start_main
  25: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

I tried to reproduce it with a minimal test case against bzip2 0.3.3 and got what appears to be an entirely different error:
```
$ cargo build --target=x86_64-pc-windows-msvc
   Compiling libc v0.2.66
   Compiling bzip2-sys v0.1.7
error: failed to run custom build command for `bzip2-sys v0.1.7`

Caused by:
  process didn't exit successfully: `/home/x/dev/rust/bzip2test/target/debug/build/bzip2-sys-86f222c7d48fea1e/build-script-build` (exit code: 1)
--- stdout
TARGET = Some("x86_64-pc-windows-msvc")
OPT_LEVEL = Some("0")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-pc-windows-msvc = None
CC_x86_64_pc_windows_msvc = None
TARGET_CC = None
CC = None
CROSS_COMPILE = None
CFLAGS_x86_64-pc-windows-msvc = None
CFLAGS_x86_64_pc_windows_msvc = None
TARGET_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "bzip2-1.0.6" "-D_WIN32" "-DBZ_EXPORT" "-D_FILE_OFFSET_BITS=64" "-DBZ_NO_STDIO" "-Fo/home/x/dev/rust/bzip2test/target/x86_64-pc-windows-msvc/debug/build/bzip2-sys-1f1ad99dbefe35b6/out/lib/bzip2-1.0.6/blocksort.o" "-c" "bzip2-1.0.6/blocksort.c"
cargo:warning=In file included from bzip2-1.0.6/bzlib_private.h:33,
cargo:warning=                 from bzip2-1.0.6/blocksort.c:22:
cargo:warning=bzip2-1.0.6/bzlib.h:70: warning: "BZ_EXPORT" redefined
cargo:warning=   70 | #define BZ_EXPORT
cargo:warning=      | 
cargo:warning=<command-line>: note: this is the location of the previous definition
cargo:warning=In file included from bzip2-1.0.6/bzlib_private.h:33,
cargo:warning=                 from bzip2-1.0.6/blocksort.c:22:
cargo:warning=bzip2-1.0.6/bzlib.h:79:13: fatal error: windows.h: No such file or directory
cargo:warning=   79 | #   include <windows.h>
cargo:warning=      |             ^~~~~~~~~~~
cargo:warning=compilation terminated.
exit code: 1

--- stderr


error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "bzip2-1.0.6" "-D_WIN32" "-DBZ_EXPORT" "-D_FILE_OFFSET_BITS=64" "-DBZ_NO_STDIO" "-Fo/home/x/dev/rust/bzip2test/target/x86_64-pc-windows-msvc/debug/build/bzip2-sys-1f1ad99dbefe35b6/out/lib/bzip2-1.0.6/blocksort.o" "-c" "bzip2-1.0.6/blocksort.c" with args "cc" did not execute successfully (status code exit code: 1).



warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by alexcrichton** [comment]
Thanks for the report, but this is unfortunately something I don't have time to help with. This is not a bug in this crate but it's something that's very difficult to set up.
